version : '3.7'
services: 
  nexus-kuzzle-nodejs-script: 
    build: 
      context: '.'
    environment: 
      - KUZZLE_HOST=${KUZZLE_HOST}
    networks:
      - nexus-network

networks:
  nexus-network:
    name: nexus-network
    driver: bridge    